using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Replaces the perfectly planar diamond-leaf failure mode in the generated fallback foliage with a
/// deterministic, shallow midrib fold while retaining the existing eight-vertex/two-sided topology.
///
/// The high-detail tree generator intentionally remains the owner of placement, branches, cluster count
/// and LOD population. This pass only changes lamina vertex positions inside the generated mesh assets.
/// It is wired to benchmark-scene saves because upstream tree-detail rebuilds intentionally regenerate
/// the three base sprays; folding them immediately after that save makes subsequent morphology variants
/// inherit the same physical lamina construction without a second hidden random process.
///
/// Source geometry checks reduce risk only. Native 3840x2160 still/temporal pixels remain authoritative
/// for silhouette naturalness, shimmer, transmission balance and the Vegetation Visual Fidelity score.
/// </summary>
[InitializeOnLoad]
public static class QualityBlockFoliageLaminaGeometryUpgrade
{
    public const string ScenePath = "Assets/Scenes/QualityBlock1990s.unity";
    public const string ContractPath = "Assets/QA/foliage_lamina_geometry_contract.json";
    public const string MeshRoot = "Assets/Art/GeneratedTreeMeshes";
    public const int VerticesPerLeaf = 8;
    public const int TriangleIndicesPerLeaf = 12;
    public const float MinimumFoldDegrees = 3.0f;
    public const float MaximumFoldDegrees = 28.0f;

    private static readonly string[] BaseMeshNames =
    {
        "GM_LeafSpray_A",
        "GM_LeafSpray_B",
        "GM_LeafSpray_C",
    };

    private static bool applying;

    static QualityBlockFoliageLaminaGeometryUpgrade()
    {
        EditorSceneManager.sceneSaved -= OnSceneSaved;
        EditorSceneManager.sceneSaved += OnSceneSaved;
    }

    [MenuItem("NewTown/Geometry/Build Folded Foliage Lamina Geometry")]
    public static void BuildAndApply()
    {
        if (!EditorSceneManager.GetActiveScene().IsValid() ||
            EditorSceneManager.GetActiveScene().path != ScenePath)
            EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);

        // Build the existing deterministic morphology first. If the base sprays were freshly
        // regenerated by the tree pass, the scene-save binding below already folded them; if this
        // menu is invoked on an older scene, the explicit library pass below converges both base and
        // derived assets to the same physical construction.
        QualityBlockFoliageMorphologyVariationUpgrade.ApplyToOpenScene();
        UpgradeGeneratedMeshLibrary(true, true);
        ValidateGeneratedMeshLibrary(true);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("Folded foliage lamina geometry built. Native 4K silhouette/shimmer review remains pending.");
    }

    [MenuItem("NewTown/QA/Validate Folded Foliage Lamina Geometry")]
    public static void ValidateMenu()
    {
        ValidateGeneratedMeshLibrary(true);
        Debug.Log("Foliage lamina source geometry passed: non-planar midrib folds are present. Render verification remains pending.");
    }

    public static void ValidateGeneratedMeshLibrary(bool requireDerivedVariants)
    {
        int validated = 0;
        foreach (string path in EnumerateRequiredPaths(requireDerivedVariants))
        {
            Mesh mesh = AssetDatabase.LoadAssetAtPath<Mesh>(path);
            if (mesh == null)
                throw new FileNotFoundException("Required foliage lamina mesh is missing: " + path);
            ValidateMesh(mesh, path);
            validated++;
        }

        int expected = BaseMeshNames.Length + (requireDerivedVariants ? QualityBlockFoliageMorphologyVariationUpgrade.VariantCount : 0);
        if (validated != expected)
            throw new InvalidOperationException($"Validated {validated} foliage lamina meshes, expected {expected}.");
    }

    /// <summary>
    /// Applies the fold to any generated spray still using the legacy perfectly-planar lamina.
    /// Already-folded assets are not folded a second time.
    /// </summary>
    public static int UpgradeGeneratedMeshLibrary(bool includeDerivedVariants, bool requireAll)
    {
        if (applying)
            return 0;

        applying = true;
        int changed = 0;
        try
        {
            foreach (string path in EnumerateRequiredPaths(includeDerivedVariants))
            {
                Mesh mesh = AssetDatabase.LoadAssetAtPath<Mesh>(path);
                if (mesh == null)
                {
                    if (requireAll)
                        throw new FileNotFoundException("Required foliage mesh is missing before lamina fold: " + path);
                    continue;
                }

                ValidateTopology(mesh, path);
                if (MeshAlreadyFolded(mesh))
                    continue;

                ApplyFold(mesh, StablePathSeed(path));
                EditorUtility.SetDirty(mesh);
                changed++;
            }

            if (changed > 0)
                AssetDatabase.SaveAssets();
            return changed;
        }
        finally
        {
            applying = false;
        }
    }

    private static void OnSceneSaved(Scene scene)
    {
        if (applying || !scene.IsValid() || !string.Equals(scene.path, ScenePath, StringComparison.Ordinal))
            return;

        try
        {
            // Base sprays always exist after the high-detail tree generator. Derived variants may not
            // exist on the first save, so they are opportunistic here; once morphology has generated
            // them from the already-folded bases they naturally inherit the fold.
            int changed = UpgradeGeneratedMeshLibrary(true, false);
            if (changed > 0)
                Debug.Log($"Foliage lamina save binding folded {changed} generated spray mesh asset(s) before downstream lookdev/capture.");
        }
        catch (Exception ex)
        {
            // A save callback must not silently corrupt the scene. Leave the malformed asset untouched;
            // formal QA will fail closed before native evidence can be sealed.
            Debug.LogException(ex);
        }
    }

    private static IEnumerable<string> EnumerateRequiredPaths(bool includeDerivedVariants)
    {
        foreach (string name in BaseMeshNames)
            yield return MeshRoot + "/" + name + ".asset";

        if (!includeDerivedVariants)
            yield break;

        for (int i = 0; i < QualityBlockFoliageMorphologyVariationUpgrade.VariantCount; i++)
            yield return MeshRoot + $"/GM_LeafSpray_Morph_{i:D2}.asset";
    }

    private static void ApplyFold(Mesh mesh, int meshSeed)
    {
        Vector3[] vertices = mesh.vertices;
        int leafCount = vertices.Length / VerticesPerLeaf;

        for (int leaf = 0; leaf < leafCount; leaf++)
        {
            int first = leaf * VerticesPerLeaf;
            Vector3 tip = vertices[first + 0];
            Vector3 right = vertices[first + 1];
            Vector3 basePoint = vertices[first + 2];
            Vector3 left = vertices[first + 3];

            Vector3 longitudinal = tip - basePoint;
            Vector3 lateral = right - left;
            float length = longitudinal.magnitude;
            float width = lateral.magnitude;
            if (length < 0.025f || width < 0.010f)
                throw new InvalidOperationException($"Leaf {leaf} in {mesh.name} is degenerate before lamina fold ({length:F4}m x {width:F4}m in mesh space).");

            Vector3 longDir = longitudinal / length;
            Vector3 lateralDir = lateral / width;
            Vector3 normal = Vector3.Cross(lateralDir, longDir).normalized;
            if (!FiniteVector(normal) || normal.sqrMagnitude < 0.9f)
                throw new InvalidOperationException($"Leaf {leaf} in {mesh.name} has an invalid tangent frame before lamina fold.");

            // A shallow V around the tip-to-base midrib breaks the perfectly planar card response.
            // Fold amount is intentionally proportional to lamina half-width so morphology scaling
            // remains plausible. The bounds correspond to roughly 4-18 mm edge drop on the current
            // generated leaves before per-cluster transform, not a thick solid slab.
            float halfWidth = width * 0.5f;
            float foldFraction = Mathf.Lerp(0.085f, 0.155f, Hash01(meshSeed, leaf, 401));
            float foldDepth = halfWidth * foldFraction;
            float cupSign = Hash01(meshSeed, leaf, 409) < 0.5f ? -1f : 1f;
            float rightDepth = foldDepth * Mathf.Lerp(0.88f, 1.12f, Hash01(meshSeed, leaf, 419));
            float leftDepth = foldDepth * Mathf.Lerp(0.88f, 1.12f, Hash01(meshSeed, leaf, 421));

            // Small petiole/lamina asymmetry avoids a mechanically perfect diamond without changing
            // cluster attachment or inventing tears/damage. Longitudinal offsets stay below 4% of
            // leaf length; tip/base lateral offsets stay below 2% of width.
            float rightAlong = length * Mathf.Lerp(-0.035f, 0.035f, Hash01(meshSeed, leaf, 431));
            float leftAlong = length * Mathf.Lerp(-0.035f, 0.035f, Hash01(meshSeed, leaf, 433));
            float tipAcross = width * Mathf.Lerp(-0.018f, 0.018f, Hash01(meshSeed, leaf, 439));
            float baseAcross = width * Mathf.Lerp(-0.018f, 0.018f, Hash01(meshSeed, leaf, 443));

            tip += lateralDir * tipAcross;
            basePoint += lateralDir * baseAcross;
            right += longDir * rightAlong + normal * (cupSign * rightDepth);
            left += longDir * leftAlong + normal * (cupSign * leftDepth);

            // Preserve the established two-sided topology exactly. Front indices 0..3 use
            // tip/right/base/left; back indices 4..7 use tip/left/base/right with reversed winding.
            vertices[first + 0] = tip;
            vertices[first + 1] = right;
            vertices[first + 2] = basePoint;
            vertices[first + 3] = left;
            vertices[first + 4] = tip;
            vertices[first + 5] = left;
            vertices[first + 6] = basePoint;
            vertices[first + 7] = right;
        }

        mesh.vertices = vertices;
        mesh.RecalculateNormals();
        mesh.RecalculateTangents();
        mesh.RecalculateBounds();
    }

    private static void ValidateMesh(Mesh mesh, string path)
    {
        ValidateTopology(mesh, path);
        Vector3[] vertices = mesh.vertices;
        int leafCount = vertices.Length / VerticesPerLeaf;
        int foldedLeaves = 0;
        float minimumObserved = 180f;
        float maximumObserved = 0f;

        for (int leaf = 0; leaf < leafCount; leaf++)
        {
            int first = leaf * VerticesPerLeaf;
            RequireCoincident(vertices[first + 0], vertices[first + 4], mesh.name, leaf, "tip");
            RequireCoincident(vertices[first + 3], vertices[first + 5], mesh.name, leaf, "left");
            RequireCoincident(vertices[first + 2], vertices[first + 6], mesh.name, leaf, "base");
            RequireCoincident(vertices[first + 1], vertices[first + 7], mesh.name, leaf, "right");

            float fold = FoldAngleDegrees(vertices, first);
            minimumObserved = Mathf.Min(minimumObserved, fold);
            maximumObserved = Mathf.Max(maximumObserved, fold);
            if (fold >= MinimumFoldDegrees && fold <= MaximumFoldDegrees)
                foldedLeaves++;
        }

        if (foldedLeaves != leafCount)
            throw new InvalidOperationException(
                $"Foliage mesh {path} has {foldedLeaves}/{leafCount} laminae inside the {MinimumFoldDegrees:F1}-{MaximumFoldDegrees:F1} degree fold window " +
                $"(observed {minimumObserved:F2}-{maximumObserved:F2}). Perfectly planar or over-folded leaves are not formal-evidence ready.");

        if (mesh.normals == null || mesh.normals.Length != mesh.vertexCount ||
            mesh.tangents == null || mesh.tangents.Length != mesh.vertexCount ||
            mesh.uv == null || mesh.uv.Length != mesh.vertexCount)
            throw new InvalidOperationException("Foliage mesh lost complete normals/tangents/UV0 after lamina fold: " + path);
        if (!FinitePositive(mesh.bounds.size.x) || !FinitePositive(mesh.bounds.size.y) || !FinitePositive(mesh.bounds.size.z))
            throw new InvalidOperationException("Foliage mesh has invalid bounds after lamina fold: " + path);
    }

    private static void ValidateTopology(Mesh mesh, string path)
    {
        if (mesh == null || mesh.vertexCount < VerticesPerLeaf || mesh.vertexCount % VerticesPerLeaf != 0)
            throw new InvalidOperationException("Foliage mesh must contain contiguous eight-vertex lamina groups: " + path);
        int leafCount = mesh.vertexCount / VerticesPerLeaf;
        int[] triangles = mesh.triangles;
        if (triangles == null || triangles.Length != leafCount * TriangleIndicesPerLeaf)
            throw new InvalidOperationException(
                $"Foliage mesh {path} changed the canonical two-sided topology: {triangles?.Length ?? 0} triangle indices for {leafCount} leaves.");
        if (mesh.subMeshCount != 1)
            throw new InvalidOperationException("Generated foliage lamina mesh must remain one submesh: " + path);
    }

    private static bool MeshAlreadyFolded(Mesh mesh)
    {
        Vector3[] vertices = mesh.vertices;
        int leafCount = vertices.Length / VerticesPerLeaf;
        if (leafCount == 0)
            return false;

        int folded = 0;
        for (int leaf = 0; leaf < leafCount; leaf++)
        {
            float angle = FoldAngleDegrees(vertices, leaf * VerticesPerLeaf);
            if (angle >= MinimumFoldDegrees * 0.75f)
                folded++;
        }
        return folded == leafCount;
    }

    private static float FoldAngleDegrees(Vector3[] vertices, int first)
    {
        Vector3 tip = vertices[first + 0];
        Vector3 right = vertices[first + 1];
        Vector3 basePoint = vertices[first + 2];
        Vector3 left = vertices[first + 3];
        Vector3 rightNormal = Vector3.Cross(right - tip, basePoint - tip).normalized;
        Vector3 leftNormal = Vector3.Cross(basePoint - tip, left - tip).normalized;
        if (!FiniteVector(rightNormal) || !FiniteVector(leftNormal) || rightNormal.sqrMagnitude < 0.9f || leftNormal.sqrMagnitude < 0.9f)
            return 180f;
        return Vector3.Angle(rightNormal, leftNormal);
    }

    private static void RequireCoincident(Vector3 a, Vector3 b, string mesh, int leaf, string label)
    {
        if ((a - b).sqrMagnitude > 0.00000025f)
            throw new InvalidOperationException($"Foliage mesh {mesh} leaf {leaf} lost front/back {label} coincidence.");
    }

    private static int StablePathSeed(string value)
    {
        unchecked
        {
            uint hash = 2166136261u;
            for (int i = 0; i < value.Length; i++)
            {
                hash ^= value[i];
                hash *= 16777619u;
            }
            return (int)(hash & 0x7FFFFFFF);
        }
    }

    private static float Hash01(int a, int b, int c)
    {
        unchecked
        {
            uint x = (uint)(a * 73856093) ^ (uint)(b * 19349663) ^ (uint)(c * 83492791);
            x ^= x >> 13;
            x *= 1274126177u;
            x ^= x >> 16;
            return (x & 0x00FFFFFFu) / 16777215f;
        }
    }

    private static bool FiniteVector(Vector3 value)
    {
        return IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z);
    }

    private static bool FinitePositive(float value)
    {
        return IsFinite(value) && value > 0f;
    }

    private static bool IsFinite(float value)
    {
        return !float.IsNaN(value) && !float.IsInfinity(value);
    }
}
